import type { Referral, Patient, Profile, Institution, Notification } from '@/types'
import { subDays, format } from 'date-fns'

export const mockInstitutions: Institution[] = [
  {
    id: 'inst-1',
    name: '台大醫院',
    code: 'NTU001',
    type: 'medical_center',
    address: '台北市中正區中山南路7號',
    phone: '02-23123456',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inst-2',
    name: '台北榮總',
    code: 'VGH001',
    type: 'medical_center',
    address: '台北市北投區石牌路二段201號',
    phone: '02-28712121',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inst-3',
    name: '新光醫院',
    code: 'SKH001',
    type: 'hospital',
    address: '台北市士林區文昌路95號',
    phone: '02-28332211',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inst-4',
    name: '長春診所',
    code: 'CLN001',
    type: 'clinic',
    address: '台北市中山區長春路100號',
    phone: '02-25018888',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockPatients: Patient[] = [
  {
    id: 'pat-1',
    institution_id: 'inst-4',
    id_hash: 'abc123hash',
    chart_no: 'C2024001',
    name_masked: '王○明',
    birth_year: 1958,
    gender: 'M',
    blood_type: 'A',
    nhi_card_valid: true,
    phone_masked: '****5678',
    primary_diagnosis: 'E11.9',
    chronic_conditions: ['高血壓', '第二型糖尿病'],
    allergies: ['Penicillin'],
    insurance_type: 'NHI',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pat-2',
    institution_id: 'inst-4',
    id_hash: 'def456hash',
    chart_no: 'C2024002',
    name_masked: '林○芳',
    birth_year: 1965,
    gender: 'F',
    blood_type: 'B',
    nhi_card_valid: true,
    phone_masked: '****2345',
    primary_diagnosis: 'I10',
    chronic_conditions: ['高血壓', '高血脂'],
    allergies: [],
    insurance_type: 'NHI',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pat-3',
    institution_id: 'inst-4',
    id_hash: 'ghi789hash',
    chart_no: 'C2024003',
    name_masked: '陳○成',
    birth_year: 1942,
    gender: 'M',
    blood_type: 'O',
    nhi_card_valid: true,
    phone_masked: '****9012',
    primary_diagnosis: 'N18.3',
    chronic_conditions: ['慢性腎臟病 Stage 3', '糖尿病', '高血壓'],
    allergies: ['Sulfonamides'],
    insurance_type: 'NHI',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pat-4',
    institution_id: 'inst-4',
    id_hash: 'jkl012hash',
    chart_no: 'C2024004',
    name_masked: '張○美',
    birth_year: 1970,
    gender: 'F',
    blood_type: 'AB',
    nhi_card_valid: false,
    phone_masked: '****3456',
    primary_diagnosis: 'J18.9',
    chronic_conditions: ['氣喘'],
    allergies: [],
    insurance_type: 'NHI',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

const today = new Date()

export const mockReferrals: Referral[] = [
  {
    id: 'ref-1',
    referral_no: 'REF-2024-000001',
    patient_id: 'pat-1',
    direction: 'upward',
    from_institution_id: 'inst-4',
    to_institution_id: 'inst-1',
    referral_reason: '血糖控制不佳，建議轉介內分泌科進一步評估',
    diagnosis_code: 'E11.9',
    diagnosis_name: '第二型糖尿病，未指明之併發症',
    urgency: 'routine',
    status: 'in_treatment',
    referral_date: format(subDays(today, 12), 'yyyy-MM-dd'),
    appointment_date: format(subDays(today, 8), 'yyyy-MM-dd'),
    actual_visit_date: format(subDays(today, 8), 'yyyy-MM-dd'),
    nhi_approved: true,
    nhi_code: 'NHI20240301',
    copayment_exempted: false,
    created_by: 'prof-1',
    created_at: subDays(today, 12).toISOString(),
    updated_at: subDays(today, 8).toISOString(),
    patient: mockPatients[0],
    from_institution: mockInstitutions[3],
    to_institution: mockInstitutions[0],
  },
  {
    id: 'ref-2',
    referral_no: 'REF-2024-000002',
    patient_id: 'pat-2',
    direction: 'upward',
    from_institution_id: 'inst-4',
    to_institution_id: 'inst-2',
    referral_reason: '頑固性高血壓，多種藥物控制不佳，需心臟科評估',
    diagnosis_code: 'I10',
    diagnosis_name: '原發性（必要性）高血壓',
    urgency: 'urgent',
    status: 'pending',
    referral_date: format(subDays(today, 2), 'yyyy-MM-dd'),
    nhi_approved: false,
    copayment_exempted: false,
    created_by: 'prof-1',
    created_at: subDays(today, 2).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
    patient: mockPatients[1],
    from_institution: mockInstitutions[3],
    to_institution: mockInstitutions[1],
  },
  {
    id: 'ref-3',
    referral_no: 'REF-2024-000003',
    patient_id: 'pat-3',
    direction: 'upward',
    from_institution_id: 'inst-4',
    to_institution_id: 'inst-1',
    referral_reason: '腎功能持續惡化（eGFR 35），建議腎臟科接手追蹤',
    diagnosis_code: 'N18.3',
    diagnosis_name: '慢性腎臟病，第三期',
    urgency: 'urgent',
    status: 'no_show',
    referral_date: format(subDays(today, 14), 'yyyy-MM-dd'),
    appointment_date: format(subDays(today, 10), 'yyyy-MM-dd'),
    nhi_approved: true,
    nhi_code: 'NHI20240302',
    copayment_exempted: true,
    created_by: 'prof-1',
    created_at: subDays(today, 14).toISOString(),
    updated_at: subDays(today, 10).toISOString(),
    patient: mockPatients[2],
    from_institution: mockInstitutions[3],
    to_institution: mockInstitutions[0],
  },
  {
    id: 'ref-4',
    referral_no: 'REF-2024-000004',
    patient_id: 'pat-4',
    direction: 'downward',
    from_institution_id: 'inst-1',
    to_institution_id: 'inst-4',
    referral_reason: '肺炎住院治療完成，建議轉回基層診所繼續追蹤',
    diagnosis_code: 'J18.9',
    diagnosis_name: '肺炎，未指明',
    urgency: 'routine',
    status: 'completed',
    referral_date: format(subDays(today, 5), 'yyyy-MM-dd'),
    appointment_date: format(subDays(today, 3), 'yyyy-MM-dd'),
    actual_visit_date: format(subDays(today, 3), 'yyyy-MM-dd'),
    completion_date: format(subDays(today, 3), 'yyyy-MM-dd'),
    treatment_summary: '住院7天，抗生素治療完成，胸部X光顯示肺炎已改善',
    followup_instructions: '建議2週後回診複查，注意是否有復發症狀',
    return_date: format(subDays(today, -11), 'yyyy-MM-dd'),
    nhi_approved: true,
    copayment_exempted: false,
    created_by: 'prof-2',
    created_at: subDays(today, 5).toISOString(),
    updated_at: subDays(today, 3).toISOString(),
    patient: mockPatients[3],
    from_institution: mockInstitutions[0],
    to_institution: mockInstitutions[3],
  },
  {
    id: 'ref-5',
    referral_no: 'REF-2024-000005',
    patient_id: 'pat-1',
    direction: 'downward',
    from_institution_id: 'inst-1',
    to_institution_id: 'inst-4',
    referral_reason: '胰島素調整完成，返回基層持續追蹤',
    diagnosis_code: 'E11.9',
    diagnosis_name: '第二型糖尿病，未指明之併發症',
    urgency: 'routine',
    status: 'returned',
    referral_date: format(subDays(today, 1), 'yyyy-MM-dd'),
    treatment_summary: 'HbA1c 由 9.2% 降至 7.8%，胰島素劑量已調整',
    followup_instructions: '每3個月回診，持續監測HbA1c、腎功能',
    nhi_approved: true,
    copayment_exempted: false,
    created_by: 'prof-2',
    created_at: subDays(today, 1).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
    patient: mockPatients[0],
    from_institution: mockInstitutions[0],
    to_institution: mockInstitutions[3],
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'prof-1',
    referral_id: 'ref-3',
    type: 'overdue',
    title: '⚠️ 個案逾期未就診',
    message: '個案 陳○成 (REF-2024-000003) 已逾 10 天未就診，請個管師聯繫確認。',
    is_read: false,
    created_at: subDays(today, 1).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'prof-1',
    referral_id: 'ref-5',
    type: 'report_received',
    title: '回報已接收',
    message: '台大醫院已完成個案 王○明 的治療，並回傳治療摘要。',
    is_read: false,
    created_at: subDays(today, 1).toISOString(),
  },
  {
    id: 'notif-3',
    user_id: 'prof-1',
    referral_id: 'ref-4',
    type: 'status_changed',
    title: '轉診狀態更新',
    message: '個案 張○美 (REF-2024-000004) 轉診狀態已更新為「已完成」。',
    is_read: true,
    created_at: subDays(today, 3).toISOString(),
  },
]

export const mockDashboardStats = {
  totalReferrals: 127,
  pendingReferrals: 18,
  completedThisMonth: 42,
  successRate: 87.4,
  overdueCount: 3,
  avgCompletionDays: 6.2,
  monthlyTrend: [
    { month: '10月', upward: 28, downward: 15, completed: 38 },
    { month: '11月', upward: 32, downward: 18, completed: 44 },
    { month: '12月', upward: 25, downward: 12, completed: 33 },
    { month: '1月', upward: 35, downward: 20, completed: 48 },
    { month: '2月', upward: 29, downward: 16, completed: 40 },
    { month: '3月', upward: 38, downward: 22, completed: 52 },
  ],
  statusDistribution: [
    { status: '待處理', count: 18, fill: '#EAB308' },
    { status: '已掛號', count: 12, fill: '#3B82F6' },
    { status: '治療中', count: 8, fill: '#8B5CF6' },
    { status: '已完成', count: 42, fill: '#22C55E' },
    { status: '未就診', count: 3, fill: '#EF4444' },
    { status: '已下轉', count: 15, fill: '#14B8A6' },
  ],
}
